packages:
  - "apps/*"
  - "components/**/*"
  - "packages/*"
  # - "devapps/*"
  - "testapps/*"
  - "examples/*"
  - "!examples/langchain-llama2-chatbot-sagemaker/comparison/*"
  - "!components/deducers/python-pyright/libs/*"
