name: Build Docker Images

on:
  repository_dispatch:
    types: [trigger-build-docker-images]
  workflow_dispatch:
    inputs:
      pluto_version:
        description: "The version of @plutolang/cli to build docker images for."
        required: true
        default: "0.4.0"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {} #reset
jobs:
  build-docker-images:
    name: Build Docker Images
    if: github.repository == 'pluto-lang/pluto'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: plutolang
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Build Script
        run: |
          bash ./scripts/build-docker-images.sh --pluto $VERSION
        env:
          VERSION: ${{ github.event.client_payload.version || inputs.pluto_version }}
